SELECT DATE_FORMAT(o.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, o.PRODUCT_ID, o.USER_ID, o.SALES_AMOUNT
FROM ONLINE_SALE o
WHERE DATE_FORMAT(o.SALES_DATE, "%Y-%m") = '2022-03'

UNION ALL

SELECT DATE_FORMAT(f.SALES_DATE, "%Y-%m-%d") AS SALES_DATE, f.PRODUCT_ID, NULL AS USER_ID, f.SALES_AMOUNT
FROM OFFLINE_SALE f
WHERE DATE_FORMAT(f.SALES_DATE, "%Y-%m") = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID