WITH PROTECTION_PERIOD AS (
    SELECT I.ANIMAL_ID, I.NAME,
        DATEDIFF(DATE(O.DATETIME), DATE(I.DATETIME)) AS DATE
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DATE DESC
)

SELECT ANIMAL_ID, NAME
FROM PROTECTION_PERIOD
LIMIT 2