WITH RECURSIVE GENERATION_DATA AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GENERATION_DATA G
        ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, G.GENERATION
FROM GENERATION_DATA G
LEFT JOIN ECOLI_DATA C
    ON G.ID = C.PARENT_ID
WHERE C.ID IS NULL
GROUP BY G.GENERATION
ORDER BY G.GENERATION