# WITH SALES AS (
#     SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
#     FROM USED_GOODS_BOARD
#     WHERE STATUS = 'DONE'
#     GROUP BY WRITER_ID
# )

# SELECT U.USER_ID, 
#         U.NICKNAME,
#         S.TOTAL_SALES
# FROM USED_GOODS_USER U
# JOIN SALES S
# ON U.USER_ID = S.WRITER_ID
# WHERE TOTAL_SALES >= 700000
# ORDER BY S.TOTAL_SALES















WITH FINISH_TRADE AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000
)

SELECT U.USER_ID AS USER_ID, 
        U.NICKNAME AS NICKNAME, 
        TOTAL_SALES AS TOTAL_SALES
FROM FINISH_TRADE F
JOIN USED_GOODS_USER U
ON F.WRITER_ID = U.USER_ID
ORDER BY TOTAL_SALES