WITH C AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
            ORDER BY CNT DESC
            LIMIT 1
)

SELECT M.MEMBER_NAME, R.REVIEW_TEXT, R.REVIEW_DATE
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R
ON M.MEMBER_ID = R.MEMBER_ID
JOIN C
    ON M.MEMBER_ID = C.MEMBER_ID
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT