# SELECT BOOK_ID, PUBLISHED_DATE
# FROM BOOK
# WHERE CATEGORY = '인문'
#     AND PUBLISHED_DATE >= '2021-01-01'
#     AND PUBLISHED_DATE < '2022-01-01'
# ORDER BY PUBLISHED_DATE;

SELECT BOOK_ID,
       DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문'
  AND DATE_FORMAT(PUBLISHED_DATE, '%Y') = '2021'
ORDER BY PUBLISHED_DATE;