WITH SALARIES AS (
    SELECT DEPT_ID, AVG(SAL) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT DISTINCT D.DEPT_ID, D.DEPT_NAME_EN, ROUND(S.AVG_SAL) AS AVG_SAL
FROM HR_DEPARTMENT D
JOIN HR_EMPLOYEES E
ON D.DEPT_ID = E.DEPT_ID
JOIN SALARIES S
ON D.DEPT_ID = S.DEPT_ID
ORDER BY AVG_SAL DESC