WITH FISH_LENGTH AS (
    SELECT ID,
            FISH_TYPE,
            CASE 
                WHEN LENGTH IS NULL THEN 10
                ELSE LENGTH
            END AS LENGTH
    FROM FISH_INFO
)

SELECT COUNT(*) AS FISH_COUNT,
       MAX(LENGTH) AS MAX_LENGTH,
       FISH_TYPE
FROM FISH_INFO
GROUP BY FISH_TYPE
HAVING AVG(
    CASE
        WHEN LENGTH IS NULL THEN 10
        ELSE LENGTH
    END
) >= 33
ORDER BY FISH_TYPE;