WITH SKILLS AS (
    SELECT 
        SUM(CASE WHEN CATEGORY = 'Front End' THEN CODE ELSE 0 END) AS FRONT_END,
        MAX(CASE WHEN NAME = 'Python' THEN CODE END) AS PYTHON,
        MAX(CASE WHEN NAME = 'C#' THEN CODE END) AS CSHARP
    FROM SKILLCODES
)

SELECT
    CASE
        WHEN (D.SKILL_CODE & S.FRONT_END) > 0
        AND (D.SKILL_CODE & S.PYTHON) > 0
            THEN 'A'
        WHEN (D.SKILL_CODE & S.CSHARP) > 0
            THEN 'B'
        WHEN (D.SKILL_CODE & S.FRONT_END) > 0
            THEN 'C'
    END AS GRADE,
    D.ID,
    D.EMAIL
FROM DEVELOPERS D
CROSS JOIN SKILLS S
WHERE (D.SKILL_CODE & S.FRONT_END) > 0
    OR (D.SKILL_CODE & S.CSHARP) > 0
ORDER BY GRADE, D.ID